version: "3.8"

services:
  repbl:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:3000
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
